### Output
outdir: logs
mesh_format: obj
save_path: None

### Dataset
dataset:
  name: ZJU
  path: ./data/ZJUMOCAP/CoreView_313
  # camera_list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
  camera_list: [1,]
  num_workers: 4

### Training
# guidance loss weights (0 to disable)
lambda_sd: 1
mvdream: False
lambda_zero123: 0
# training batch size per iter
batch_size: 1
# training iterations for stage 1
iters: 500
# whether to linearly anneal timestep
anneal_timestep: True
# training iterations for stage 2
iters_refine: 50
# training camera radius
radius: 2.5
# training camera fovy
fovy: 49.1
# checkpoint to load for stage 1 (should be a ply file)
load:
# whether allow geom training in stage 2
train_geo: False
# prob to invert background color during training (0 = always black, 1 = always white)
invert_bg_prob: 0.5

lr: 0.0001

### GUI
gui: False
force_cuda_rast: False
# GUI resolution
H: 1024
W: 1024
near: 0.1
far: 100

### Gaussian splatting
num_pts: 5000
sh_degree: 0
position_lr_init: 0.001
position_lr_final: 0.00002
position_lr_delay_mult: 0.02
position_lr_max_steps: 300
feature_lr: 0.01
opacity_lr: 0.05
scaling_lr: 0.005
rotation_lr: 0.005
percent_dense: 0.01
density_start_iter: 0
density_end_iter: 3000
densification_interval: 50
opacity_reset_interval: 700
densify_grad_threshold: 0.01

### Textured Mesh
geom_lr: 0.0001
texture_lr: 0.2